/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-03-06 12:38:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welComePageNetflix_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footerNetflix.jsp", Long.valueOf(1520303034279L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Bootstrap 4 Example</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"></script>\r\n");
      out.write("<script\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body\r\n");
      out.write("\tbackground=\"C:/Users/bhara/eclipse-workspace/netflix-operation/src/main/webapp/img/lofoten-fishing-village-nordland-county-norway-europe-mountains-geography.jpg\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<h1 style=\"color: red; float: left; display: inline;\">\r\n");
      out.write("\t\t\t<strong>NETFLIX</strong>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<ul class=\"nav\" style=\"float: right; padding: 20px 20px 0 20px\">\r\n");
      out.write("\t\t<li class=\"nav-item\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-danger\">Sign In</button>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<br>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-fluid\" style=\"float: left;\">\r\n");
      out.write("\t\t<div class=\"col-sm-6\" style=\"padding: 90px 0 0 0\">\r\n");
      out.write("\t\t\t<h1 style=\"font-size: 42px; color: #ffffff;\">See What's Next.</h1>\r\n");
      out.write("\t\t\t<h2 style=\"font-size: 28px; color: #ffffff;\">WATCH ANYWHERE.\r\n");
      out.write("\t\t\t\tCANCEL ANYTIME.</h2>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-danger\">JOIN FREE FOR A\r\n");
      out.write("\t\t\t\tMONTH</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div class=\"container\"  style=\"display:inline;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info\" align=\"center\" data-toggle=\"collapse\" data-target=\"#demo\">Simple collapsible</button>\r\n");
      out.write("\t\t\t<div id=\"demo\" class=\"collapse\">Lorem ipsum dolor sit amet,\r\n");
      out.write("\t\t\t\tconsectetur adipisicing elit, sed do eiusmod tempor incididunt ut\r\n");
      out.write("\t\t\t\tlabore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\r\n");
      out.write("\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\t\tconsequat.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info\" align=\"center\" data-toggle=\"collapse\" data-target=\"#demo\">Simple\tcollapsible</button>\r\n");
      out.write("\t\t\t<div id=\"demo\" class=\"collapse\">Lorem ipsum dolor sit amet,\r\n");
      out.write("\t\t\t\tconsectetur adipisicing elit, sed do eiusmod tempor incididunt ut\r\n");
      out.write("\t\t\t\tlabore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\r\n");
      out.write("\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\t\tconsequat.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-info\" align=\"center\" data-toggle=\"collapse\" data-target=\"#demo\">Simple collapsible</button>\r\n");
      out.write("\t\t\t<div id=\"demo\" class=\"collapse\">Lorem ipsum dolor sit amet,\r\n");
      out.write("\t\t\t\tconsectetur adipisicing elit, sed do eiusmod tempor incididunt ut\r\n");
      out.write("\t\t\t\tlabore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud\r\n");
      out.write("\t\t\t\texercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("\t\t\t\tconsequat.\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"carousel-slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("       <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("        <li data-target=\"#myCarousel\" data-slide-to=\"4\"></li>\r\n");
      out.write("         <li data-target=\"#myCarousel\" data-slide-to=\"5\"></li>\r\n");
      out.write("          <li data-target=\"#myCarousel\" data-slide-to=\"6\"></li>\r\n");
      out.write("           <li data-target=\"#myCarousel\" data-slide-to=\"7\"></li>\r\n");
      out.write("            <li data-target=\"#myCarousel\" data-slide-to=\"8\"></li>\r\n");
      out.write("             <li data-target=\"#myCarousel\" data-slide-to=\"9\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("        <img src=\"1.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"2.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"3.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"item \">\r\n");
      out.write("        <img src=\"4.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"item \">\r\n");
      out.write("        <img src=\"5.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"item \">\r\n");
      out.write("        <img src=\"6.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"item\">\r\n");
      out.write("        <img src=\"7.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"item\">\r\n");
      out.write("        <img src=\"8.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("       <div class=\"item\">\r\n");
      out.write("        <img src=\"9.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"10.jpg\" class=\"img-fluid\" style=\"width:20%;\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Bootstrap 4 Example</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:black;\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<p>Question? Call 1-866-579-7172</p>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">FAQ</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Investor Relations</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Terms of Use</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Contact Us</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Help Center</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Jobs</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Privacy</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Speed Test</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Account</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Gift Cards</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Cookie Preferences</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Netflix Originals</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Media Center</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Ways to Watch</button>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-link\">Corporate\r\n");
      out.write("\t\t\tInformation</button>\r\n");
      out.write("\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-secondary dropdown-toggle\" type=\"button\"\r\n");
      out.write("\t\t\t\tid=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\">Dropdown button</button>\r\n");
      out.write("\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Action</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Another action</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Something else here</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p align=\"center\">2017 &copy;</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
